SELECT
  _materialized_hypertable_35.datetime,
  _materialized_hypertable_35.metering_point_code,
  _materialized_hypertable_35.measure_type,
  _materialized_hypertable_35.contract_type,
  _materialized_hypertable_35.source,
  _materialized_hypertable_35.measure_unit,
  _materialized_hypertable_35.value,
  _materialized_hypertable_35.energy_basic_fee,
  _materialized_hypertable_35.energy_fee,
  _materialized_hypertable_35.price,
  _materialized_hypertable_35.spot_energy_fee_no_margin,
  _materialized_hypertable_35.spot_price_no_margin,
  _materialized_hypertable_35.transfer_basic_fee,
  _materialized_hypertable_35.transfer_fee,
  _materialized_hypertable_35.transfer_tax_fee,
  _materialized_hypertable_35.tax_percentage,
  _materialized_hypertable_35.night,
  _materialized_hypertable_35.spot_price,
  _materialized_hypertable_35.spot_price_with_tax
FROM
  _timescaledb_internal._materialized_hypertable_35
ORDER BY
  _materialized_hypertable_35.datetime;