SELECT
  _materialized_hypertable_66.datetime,
  _materialized_hypertable_66.metering_point_code,
  _materialized_hypertable_66.measure_type,
  _materialized_hypertable_66.contract_type,
  _materialized_hypertable_66.source,
  _materialized_hypertable_66.measure_unit,
  _materialized_hypertable_66.value,
  _materialized_hypertable_66.energy_basic_fee,
  _materialized_hypertable_66.energy_fee,
  _materialized_hypertable_66.price,
  _materialized_hypertable_66.spot_energy_fee_no_margin,
  _materialized_hypertable_66.spot_price_no_margin,
  _materialized_hypertable_66.transfer_basic_fee,
  _materialized_hypertable_66.transfer_fee,
  _materialized_hypertable_66.transfer_tax_fee,
  _materialized_hypertable_66.tax_percentage,
  _materialized_hypertable_66.night,
  _materialized_hypertable_66.spot_price,
  _materialized_hypertable_66.spot_price_with_tax
FROM
  _timescaledb_internal._materialized_hypertable_66
ORDER BY
  _materialized_hypertable_66.datetime;