import "@energyapp/styles/globals.css";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';

import { Inter } from "next/font/google";
import { cookies } from "next/headers";

import { TRPCReactProvider } from "@energyapp/trpc/react";
import { getServerAuthSession } from "@energyapp/server/auth";
import BottomNav from "./_components/Navigation/bottom-navigation";
import { CssBaseline } from "@mui/material";

import ThemeRegistry from "./_components/ThemeRegistry/ThemeRegistry";
import MenuAppBar from "./_components/MenuAppBar/AppBar";
import SessionProvider from "./_components/session-provider";
import AuthUpdater from "./_components/auth-updater";

import AntdTheme from "./_components/ThemeRegistry/AntdTheme";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "EnergyApp",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerAuthSession();

  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable} dark`}>
        <TRPCReactProvider cookies={cookies().toString()}>
          <AppRouterCacheProvider>
            <AntdTheme>
              <ThemeRegistry>
                <SessionProvider>
                  <CssBaseline />
                  <AuthUpdater />
                  <MenuAppBar session={session} />
                  <BottomNav session={session}>
                    {children}
                  </BottomNav>
                </SessionProvider>
              </ThemeRegistry>
            </AntdTheme>
          </AppRouterCacheProvider>
        </TRPCReactProvider>
      </body>
    </html >
  );
}
